server:
  port: 8083
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: mesho123moris
    url: jdbc:mysql://localhost:3306/webus
    username: root
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true

jwt:
  secret: webus123